site_url: http://ymlocal.com:3000
facebook_app_id: 448703455184821
twitter:
  consumer_key: dtr1ewqEc8ScGG5M0S3SBA
  consumer_secret: 7ZlCXK7RRNH7dpdJCICQZNim2nFQHfg41GOpNwTM60
  site_oauth_token: 190558659-iwamjBwoBvu1Jpz7927vLNTMZeP1HYzr7gMosXcw # Post as @gbrunei
  site_oauth_secret: o3WGbYdqdewITLPqjVgGDk6RHT4cQpXFGyjHOFg9I0
  bearer_token: AAAAAAAAAAAAAAAAAAAAAIGONQAAAAAAjy8QmcegLa1avvwJWvcPImUrsQY%3DrBDRqWhXHnpulTZdJZmtbH2lZ52PhCQU6m8lN3sI4P4  
facebook:
  site_page_access_token: CAAGcBuUjgxYBALyYXb6YBd0tCu6hW9tBwZCClyejiTr9jrUz1wMg7folpTcvqXAN8ZBjwVX6m4IMElbq0CyGyfKefMwD9DcMi1HFSttZBuvfJE3ZCBv3xmCqx1ZCZC0C5j2GyRQK6QjXlDlt61lyrmYjJzmUxzu8AYddQ32FLZC1JGxolxVz71c # Post as Yoomee Test
payment_sense:
  merchant_id: NEIGHB-3298248
  password: T46Q8G4J9F