site_url: http://ymlocal.com:3000
facebook_app_id: 448703455184821
twitter:
  consumer_key: dtr1ewqEc8ScGG5M0S3SBA
  consumer_secret: 7ZlCXK7RRNH7dpdJCICQZNim2nFQHfg41GOpNwTM60
  site_oauth_token: 190558659-iwamjBwoBvu1Jpz7927vLNTMZeP1HYzr7gMosXcw # Post as @gbrunei
  site_oauth_secret: o3WGbYdqdewITLPqjVgGDk6RHT4cQpXFGyjHOFg9I0
facebook:
  site_page_access_token: CAAGcBuUjgxYBAPIYtkkSP3ZBvRPMR8ZCFRsWVrnREadSDjQEiitryNxnPTyXQYyX8DK0YcZCUfgbTJDvUdpP5ND6xcX5QxHeYmEkZAvbUGtIrV3XDLOdQ6EjdZAKBTyrJdXoqmDCf6SNifAb917FeyEStqX6uiVdPgJnZAwxgR9UP7jaOZBuuwO4BgnKKy8A7QZD # Post as Yoomee Test