site_url: http://neighbourscanhelp.org.uk
twitter:
  consumer_key: 8wFZxwLv7onfEtFKtj15HQ
  consumer_secret: 9VLODYtYbrcGUlNtHl3vLJXel2VMVSEBxOiyfJngky4
  site_oauth_token: 190558659-iwamjBwoBvu1Jpz7927vLNTMZeP1HYzr7gMosXcw # Post as @gbrunei
  site_oauth_secret: o3WGbYdqdewITLPqjVgGDk6RHT4cQpXFGyjHOFg9I0
  bearer_token: AAAAAAAAAAAAAAAAAAAAAEDZRQAAAAAAvYcfpVJjpvZb5Kk44NggAu2WABU%3DuC3LJLN6mBQbNfKpuoqL6Tkuti1GvHZLJQUhX8VoyPQ  
facebook:
  site_page_access_token: CAAGcBuUjgxYBAJix4YRpF3d5kr8vwmvAAkjr2JGDGpIuH6xMIz4HmXXohdt0EaBDeTICtE6vGKPR7pqnEoxxXOoMZCADHZAu31h353yuuMb4r7TpQJ7LOXWXIeMHGEb8yf3fX77kVFFaOlCrA3V0WqA4BDyYjJh84PLxJl8mYiTtJjhLcc # Post as Yoomee Test
payment_sense:
  merchant_id: NEIGHB-9012216
  password: s2V1c2VQxf
