site_url: http://neighbourscanhelp.org.uk
twitter:
  consumer_key: 8wFZxwLv7onfEtFKtj15HQ
  consumer_secret: 9VLODYtYbrcGUlNtHl3vLJXel2VMVSEBxOiyfJngky4
  site_oauth_token: J9Yn1Yg78Gt1EjUYMoItwxWmT8qQxc7dEb9IBlxw0k
  site_oauth_secret: jkevKjgDzxUhZrf4i7MeY1F3q7Szsd6wzaUva7NRWzw
  bearer_token: AAAAAAAAAAAAAAAAAAAAAEDZRQAAAAAAvYcfpVJjpvZb5Kk44NggAu2WABU%3DuC3LJLN6mBQbNfKpuoqL6Tkuti1GvHZLJQUhX8VoyPQ  
facebook:
  site_page_access_token: CAAGYFZBoOR7UBAMiJrJbFy1cXVaLpnEdujaMsL2heZC0zxIEG2UzTZAcAr5mKrkeAZBuRmDBpn0K6GfymW48pis4mZCeFedTI3K3axuEioz46dtk86rZBb1o8ZAG41p7pJXnGd2rx5oad9sIs8l6hExjdb9s3nAyvPOoNE7o38Uf2mCRSfZAgNPZC
payment_sense:
  merchant_id: NEIGHB-9012216
  password: s2V1c2VQxf